# Generated by Django 2.1.9 on 2019-06-27 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
