# Generated by Django 2.1.9 on 2019-06-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_creation',
            new_name='created',
        ),
    ]
