# Generated by Django 2.1.9 on 2019-06-27 12:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
