# Generated by Django 2.1.9 on 2019-07-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-published',), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
