# Generated by Django 2.1.9 on 2019-07-12 12:38

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190708_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='events/'),
        ),
    ]
