# Generated by Django 2.1.9 on 2019-07-22 11:17

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190721_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='introtext',
            field=models.CharField(default='', max_length=300, verbose_name='Введение'),
        ),
        migrations.AddField(
            model_name='event',
            name='longtitle',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=80, verbose_name='Описание (SEO)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='events/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
