# Generated by Django 2.1.9 on 2019-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190722_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=120, verbose_name='Описание (SEO)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longtitle',
            field=models.CharField(default='', max_length=150, verbose_name='Заголовок страницы'),
        ),
    ]
