# Generated by Django 2.1.9 on 2019-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190808_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='Заголовок'),
        ),
    ]
