# Generated by Django 2.1.9 on 2019-06-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', unique=True)),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('content', models.TextField(default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='опубликовано')),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
