# Generated by Django 2.1.9 on 2019-07-12 10:17

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190626_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
