# Generated by Django 2.1.9 on 2019-07-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190716_1235'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
