# Generated by Django 2.2.1 on 2019-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnews',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
