# Generated by Django 2.1.9 on 2019-06-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_itemnews_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnews',
            old_name='text',
            new_name='title_news',
        ),
    ]
