# Generated by Django 2.1.9 on 2019-06-07 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190606_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnews',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
