# Generated by Django 2.1.9 on 2019-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_itemnews_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnews',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
