# Generated by Django 2.1.9 on 2019-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_itemnews_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnews',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
