# Generated by Django 2.1.9 on 2019-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190629_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
