# Generated by Django 2.1.9 on 2019-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_new_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
