# Generated by Django 2.1.9 on 2019-07-08 08:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190701_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
