# Generated by Django 2.1.9 on 2019-07-12 11:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190708_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='news/'),
        ),
    ]
