# Generated by Django 2.1.9 on 2019-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
