# Generated by Django 2.1.9 on 2019-06-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='page_title',
            new_name='title',
        ),
    ]
