# Generated by Django 2.1.9 on 2019-06-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pages_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
