# Generated by Django 2.1.9 on 2019-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190611_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
