# Generated by Django 2.1.9 on 2019-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190611_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницы', 'verbose_name_plural': 'Статические страницы'},
        ),
    ]
