# Generated by Django 2.1.9 on 2019-06-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190626_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницы', 'verbose_name_plural': 'Статичные страницы'},
        ),
    ]
