# Generated by Django 2.1.9 on 2019-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('date_registration', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
